### ISSUE TITLE
Erro Composer update

### ISSUE THREAD

**Issue by eborguezao** [GustavoWerle01/Pagseguro-PHP#1]
Configurei a biblioteca em Apache2/PHP7.3 e como solicitado executei o comando "composer update" mas o retorno é:

Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - phpunit/phpunit 9.1.5 requires php ^7.3 -> your PHP version (5.6.39) does not satisfy that requirement.
    - phpunit/phpunit 9.1.4 requires php ^7.3 -> your PHP version (5.6.39) does not satisfy that requirement.
    - phpunit/phpunit 9.1.3 requires php ^7.3 -> your PHP version (5.6.39) does not satisfy that requirement.
    - phpunit/phpunit 9.1.2 requires php ^7.3 -> your PHP version (5.6.39) does not satisfy that requirement.
    - phpunit/phpunit 9.1.1 requires php ^7.3 -> your PHP version (5.6.39) does not satisfy that requirement.
    - phpunit/phpunit 9.1.0 requires php ^7.3 -> your PHP version (5.6.39) does not satisfy that requirement.
    - phpunit/phpunit 9.1.4 requires php ^7.3 -> your PHP version (5.6.39) does not satisfy that requirement.
    - Installation request for phpunit/phpunit ^9.1 -> satisfiable by phpunit/phpunit[9.1.0, 9.1.1, 9.1.2, 9.1.3, 9.1.4, 9.1.5].

**Comment by gustavowerle** [comment]
Olá, neste projeto eu utilizei a versão 7.4.3. Acabei de baixar o projeto e funcionou corretamente. Tente atualizar seu PHP ou altere a versão do phpunit no arquivo "composer.json" para uma versão anterior.
![image](https://user-images.githubusercontent.com/44247086/82769972-24f4ae00-9e0d-11ea-8764-5c057e62619a.png)

**Comment by eborguezao** [comment]
Como disse eu executo em PHP 7.3, deve haver alguma incongruência por rodar no Windows, mas uso normalmente composer/phpunit em outras instâncias.

**Comment by gustavowerle** [comment]
Estava analisando melhor a sua mensagem de erro e percebi que o PHP que está sendo executado na sua maquina está na versão 5.6. Como você disse que está utilizando a versão 7.3 creio que você possui mais de uma versão instalada. Verifique as configurações das variáveis de ambiente para chamar a versão correta do PHP.
![image](https://user-images.githubusercontent.com/44247086/82848465-eec93400-9ec9-11ea-81be-02c4300830a4.png)
