### ISSUE TITLE
Warning: Unsupported declare 'strict_types' in

### ISSUE THREAD

**Issue by eborguezao** [GustavoWerle01/Pagseguro-PHP#2]
Após "composer update" e implementação, o erro abaixo é exibido, pensei que se tratava do mbstring, mas todas as dependências estão okay, mas o erro persiste.

"Warning: Unsupported declare 'strict_types' in PAGSEGURO-PHP/vendor/phpunit/phpunit/src/Framework/Assert/Functions.php on line 1"

**Comment by gustavowerle** [comment]
A função strict_types é suportada apenas nas versão do PHP 7 em diante. Verifique sua versão do PHP.

**Comment by eborguezao** [comment]
Aqui está 7.3 remoto e 7.4 local, mas fiz downgrade para 7.e e funcionou.
